export const categories = [
  { id: "fiction", name: "Fiction" },
  { id: "non-fiction", name: "Non-Fiction" },
  { id: "science", name: "Science" },
  { id: "technology", name: "Technology" },
  { id: "biography", name: "Biography" },
  { id: "history", name: "History" },
  { id: "fantasy", name: "Fantasy" },
  { id: "mystery", name: "Mystery" },
];

export const books = [
  {
    id: "1",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    description:
      "A psychological thriller about a woman who shoots her husband and then stops speaking.",
    category: "mystery",
    price: 24.99,
    rating: 4.5,
    publishedDate: "2023-01-15",
    pages: 336,
    isbn: "978-1250301697",
  },
  {
    id: "2",
    title: "Atomic Habits",
    author: "James Clear",
    description: "An easy & proven way to build good habits & break bad ones.",
    category: "non-fiction",
    price: 27.99,
    rating: 4.8,
    publishedDate: "2022-10-18",
    pages: 320,
    isbn: "978-0735211292",
  },
  {
    id: "3",
    title: "Project Hail Mary",
    author: "Andy Weir",
    description:
      "A lone astronaut must save the earth from disaster in this incredible scientific adventure.",
    category: "science",
    price: 28.99,
    rating: 4.9,
    publishedDate: "2023-03-02",
    pages: 496,
    isbn: "978-0593135204",
  },
  {
    id: "4",
    title: "The Midnight Library",
    author: "Matt Haig",
    description:
      "A novel about all the choices that go into a life well lived.",
    category: "fiction",
    price: 26.99,
    rating: 4.7,
    publishedDate: "2023-02-14",
    pages: 304,
    isbn: "978-0525559474",
  },
  {
    id: "5",
    title: "Clean Code",
    author: "Robert C. Martin",
    description:
      "A handbook of agile software craftsmanship with practical advice.",
    category: "technology",
    price: 45.99,
    rating: 4.6,
    publishedDate: "2022-11-30",
    pages: 464,
    isbn: "978-0132350884",
  },
  {
    id: "6",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    description:
      "A brief history of humankind from stone tools to Silicon Valley.",
    category: "history",
    price: 29.99,
    rating: 4.7,
    publishedDate: "2023-04-22",
    pages: 464,
    isbn: "978-0062316097",
  },
  {
    id: "7",
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    description:
      "The story of a magically gifted young man who grows to be the greatest wizard his world has ever known.",
    category: "fantasy",
    price: 31.99,
    rating: 4.8,
    publishedDate: "2023-05-10",
    pages: 662,
    isbn: "978-0756404741",
  },
  {
    id: "8",
    title: "Becoming",
    author: "Michelle Obama",
    description:
      "An intimate, powerful, and inspiring memoir by the former First Lady of the United States.",
    category: "biography",
    price: 32.99,
    rating: 4.9,
    publishedDate: "2023-01-08",
    pages: 448,
    isbn: "978-1524763138",
  },
];
